### ISSUE TITLE
使用多开的时候，akebi的命令提示符窗口会提示Failed to close mhyprot2 handle. Report this Issue and describe it.

### ISSUE THREAD

**Issue by a1047707793a** [GC-Ruth/Genshin-Impact-Point_Switch#1]
似乎是多开会导致过反作弊不成功，请问作者有和akebi的作者提到过这个问题吗

**Comment by GC-Ruth** [comment]
多开的原理是让原神无法找到mhypbase.dll文件，而mhyport2句柄是在这个dll文件里的，我使用ProcessExplorer分别扫描了：
1.正常手动打开的普通原神    结果：mhyport2句柄存在
2.使用软件多开时打开的第一个普通原神以及后续的原神   结果：mhyport2句柄不存在
3.使用作弊程序多开的原神   结果：无论打开多少个，mhyport2句柄都不存在
    综上所述：
多开时因为原神无法调用mhypbase.dll，所以不会生成mhyport2句柄，由于作弊程序可能不会判断mhyport2是否存在或者已经被关闭，所以一旦找不到mhyport2句柄，就会报错无法关闭mhyport2句柄，以上结果均为实践得出，可能会有错误

**Comment by a1047707793a** [comment]
那么理论上来说没有调用mhypbase.dll也就等于把mhyport2句柄关闭了是吗 那么也就是说其实对作弊程序是没有影响的对吧

**Comment by GC-Ruth** [comment]
![image](https://user-images.githubusercontent.com/107023226/223661336-b0563454-85b4-40a6-ac6d-4a831da98425.png)

**Comment by a1047707793a** [comment]
所以和我上述的想法一致了对吗，就是说如果这种找不到mhypbase.dll的多开方法是安全的那么就不会影响到作弊程序的安全性了？

**Comment by GC-Ruth** [comment]
如果mhy有文件检测机制，那么不能保证这是完全安全的，可能是睁一只闭一只眼
